Repository kmycode/mastodon, pull requests merged in 2023-11, with the labels that each got.

#210 Fix: 同じ投稿を返信かつ参照している時、同じ投稿が`context`に複数含まれる問題
  app/controllers/api/v1/statuses_controller.rb
  spec/controllers/api/v1/statuses_controller_spec.rb
Labels: bug

#219 Fix: ローカルサーバーのスタンプ利用可否が正しく反映できない問題
  app/models/instance_info.rb
  app/presenters/status_relationships_presenter.rb
  app/serializers/rest/status_serializer.rb
Labels: bug

#227 Add: いらないブランチをまとめて消す`yarn`コマンド
  package.json
Labels: enhancement

#226 Upstream 20231103
  app/services/fan_out_on_write_service.rb
  app/workers/thread_resolve_worker.rb
  spec/lib/activitypub/activity/create_spec.rb
Labels: upstream

#232 Change: #185 『スタンプをつけられた人』ではなく『スタンプをつけた人』のフォロワーにスタンプを転送
  app/controllers/api/v1/statuses/emoji_reactions_controller.rb
  app/lib/activitypub/activity/like.rb
  app/lib/activitypub/activity/undo.rb
  app/lib/status_reach_finder.rb
  app/services/emoji_react_service.rb
  app/services/un_emoji_react_service.rb
  app/workers/activitypub/emoji_reaction_distribution_worker.rb
  spec/services/emoji_react_service_spec.rb
  spec/services/un_emoji_react_service_spec.rb
Labels: server-test-requested

#242 Fix: #241 リスト新着通知で、数日前の古い投稿についての通知が来る場合がある
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/workers/feed_insert_worker.rb
Labels: server-test-requested

#249 Fix: フレンドサーバーに投稿削除が配送されない問題
  app/services/remove_status_service.rb
Labels: bug, cost-low, federation

#251 Change: スタンプの`id`をお気に入りと区別できるよう変更
  app/serializers/activitypub/emoji_reaction_serializer.rb
Labels: specchange, federation

#256 Add: スタンプにブロック・アカウントドメインブロックを反映
  app/lib/activitypub/activity/like.rb
  app/validators/emoji_reaction_validator.rb
  spec/lib/activitypub/activity/like_spec.rb
Labels: enhancement, privacy, federation

#257 Fix: リモートから来たスタンプの保存に失敗した時、Sidekiqジョブが再試行される問題
  app/lib/activitypub/activity/like.rb
Labels: bug

#259 Fix: #236 ログインしていない状態で投稿詳細画面でスタンプを押そうとすると画面が操作不能になる
  app/javascript/mastodon/features/status/index.jsx
Labels: backport

#261 Fix: 引用元の投稿が削除されたときにエラーが出る問題
  app/models/status.rb
Labels: bug

#262 Add: #213 右サイドメニューからお気に入りを削除するオプション
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/features/compose/containers/emoji_picker_dropdown_container.js
  app/javascript/mastodon/features/status/components/action_bar.jsx
  app/javascript/mastodon/features/status/components/detailed_status.jsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/selectors/index.js
  app/models/concerns/has_user_settings.rb
  app/models/user_settings.rb
  app/serializers/initial_state_serializer.rb
  app/views/settings/preferences/appearance/show.html.haml
  config/locales/simple_form.en.yml
  config/locales/simple_form.ja.yml
Labels: refactoring

#265 Fix: スマホで見た時、ヘッダ右側が隠れる問題
  app/javascript/styles/mastodon/components.scss
Labels: bug

#267 Upstream 20231110
  .devcontainer/Dockerfile
  .devcontainer/post-create.sh
  .github/renovate.json5
  .haml-lint_todo.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/relationships_controller.rb
  app/helpers/application_helper.rb
  app/javascript/mastodon/actions/accounts.js
  app/javascript/mastodon/api_types/accounts.ts
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/followers/index.jsx
  app/javascript/mastodon/features/following/index.jsx
  app/javascript/mastodon/features/video/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/models/account.ts
  app/lib/status_cache_hydrator.rb
  app/serializers/rest/account_serializer.rb
  app/views/layouts/application.html.haml
  config/initializers/content_security_policy.rb
  config/initializers/doorkeeper.rb
  config/initializers/paperclip.rb
  config/initializers/sidekiq.rb
  config/initializers/simple_form.rb
  config/locales/activerecord.lt.yml
  config/locales/ko.yml
  config/locales/lt.yml
  config/locales/ru.yml
  config/locales/simple_form.lt.yml
  config/routes/api.rb
  lib/tasks/mastodon.rake
  package.json
  spec/controllers/accounts_controller_spec.rb
  spec/controllers/api/v1/accounts/relationships_controller_spec.rb
  spec/fabricators/session_activation_fabricator.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/flashes_helper_spec.rb
  spec/models/concerns/remotable_spec.rb
  spec/models/session_activation_spec.rb
  spec/models/setting_spec.rb
  spec/requests/api/v1/accounts/relationships_spec.rb
  yarn.lock
Labels: upstream

#276 Test: アカウント削除時のブックマーク・スタンプなど削除のテスト
  .rubocop_todo.yml
  app/models/concerns/account_associations.rb
  app/services/delete_account_service.rb
  spec/fabricators/bookmark_category_fabricator.rb
  spec/fabricators/bookmark_category_status_fabricator.rb
  spec/services/delete_account_service_spec.rb
Labels: test

#277 Upstream 20231111
  app/controllers/api/v1/instances/activity_controller.rb
  app/controllers/api/v1/instances/base_controller.rb
  app/controllers/api/v1/instances/domain_blocks_controller.rb
  app/controllers/api/v1/instances/extended_descriptions_controller.rb
  app/controllers/api/v1/instances/languages_controller.rb
  app/controllers/api/v1/instances/peers_controller.rb
  app/controllers/api/v1/instances/privacy_policies_controller.rb
  app/controllers/api/v1/instances/rules_controller.rb
  app/controllers/api/v1/instances/translation_languages_controller.rb
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/es-AR.json
  app/javascript/mastodon/locales/es-MX.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fr-QC.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/is.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/lt.json
  app/javascript/mastodon/locales/lv.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/nn.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/sq.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  app/lib/feed_manager.rb
  config/locales/doorkeeper.lt.yml
  config/locales/fi.yml
  config/locales/ja.yml
  config/locales/lt.yml
  config/locales/lv.yml
  config/locales/simple_form.ja.yml
  package.json
  spec/controllers/settings/aliases_controller_spec.rb
  spec/controllers/settings/applications_controller_spec.rb
  spec/controllers/settings/deletes_controller_spec.rb
  spec/controllers/settings/exports_controller_spec.rb
  spec/controllers/settings/imports_controller_spec.rb
  spec/controllers/settings/login_activities_controller_spec.rb
  spec/controllers/settings/migration/redirects_controller_spec.rb
  spec/controllers/settings/migrations_controller_spec.rb
  spec/controllers/settings/preferences/appearance_controller_spec.rb
  spec/controllers/settings/preferences/notifications_controller_spec.rb
  spec/controllers/settings/preferences/other_controller_spec.rb
  spec/controllers/settings/profiles_controller_spec.rb
  spec/controllers/settings/two_factor_authentication/webauthn_credentials_controller_spec.rb
  spec/controllers/settings/two_factor_authentication_methods_controller_spec.rb
  yarn.lock
Labels: upstream

#292 Fix: セットアップスクリプトの`yarn install`でエラーが出る／`latest`を追加
  install/9.0/setup-imagemagick-7.sh
  install/9.0/setup1.sh
  install/9.0/setup2.sh
  install/9.0/setup3.sh
  install/9.0/setup4.sh
Labels: server-test-requested

#278 Release: 5.9 LTS
  lib/mastodon/version.rb
Labels: release

#279 Release: 9.0
  db/migrate/20231105225839_add_master_settings_to_accounts.rb
  lib/mastodon/version.rb
Labels: release

#283 Change: サークルの送り先アカウント指定方法を`account_username`（Fedibirdと同様）に変更
  app/lib/activitypub/tag_manager.rb
  app/lib/status_reach_finder.rb
  app/workers/activitypub/distribution_worker.rb
  spec/workers/activitypub/distribution_worker_spec.rb
Labels: specchange, backport, server-test-requested

#297 Fix/elasticsearch plugin ci failure
  .env.test
  .github/workflows/test-ruby.yml
  app/chewy/accounts_index.rb
  app/chewy/public_statuses_index.rb
  app/chewy/statuses_index.rb
Labels: test

#305 Upstream 20231128
  Gemfile.lock
  app/chewy/accounts_index.rb
  app/chewy/concerns/datetime_clamping_concern.rb
  app/chewy/public_statuses_index.rb
  app/chewy/statuses_index.rb
  app/chewy/tags_index.rb
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/locales/af.json
  app/javascript/mastodon/locales/be.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/es-AR.json
  app/javascript/mastodon/locales/es-MX.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/et.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fo.json
  app/javascript/mastodon/locales/fr-QC.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/fy.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/is.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/lt.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt-PT.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/vi.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  app/mailers/admin_mailer.rb
  app/models/concerns/attachmentable.rb
  app/views/admin/custom_emojis/new.html.haml
  app/views/layouts/plain_mailer.html.haml
  config/locales/ca.yml
  config/locales/et.yml
  config/locales/fy.yml
  config/locales/lt.yml
  config/locales/nl.yml
  config/locales/simple_form.et.yml
  config/locales/zh-TW.yml
  package.json
  streaming/package.json
  yarn.lock
Labels: upstream

#308 Change: サークルの送り先アカウント指定方法を`account_username`（Fedibirdと同様）に変更 (#283) (LTS)
  app/lib/activitypub/tag_manager.rb
  app/lib/status_reach_finder.rb
  app/workers/activitypub/distribution_worker.rb
  spec/workers/activitypub/distribution_worker_spec.rb
Labels: backport

#311 Test: フォロワーに限定投稿を配送しない
  spec/workers/activitypub/distribution_worker_spec.rb
Labels: test, backport

#313 Test: ドメインブロック先からのブースト拒否のテスト（保留中）を削除
  spec/lib/activitypub/activity/announce_spec.rb
Labels: test

#314 Fix: スタンプを外すとき、自分が外したスタンプが投稿から全部消える問題
  app/models/status.rb
  app/services/un_emoji_react_service.rb
Labels: bug, backport

#315 Upstream 20231129
  .devcontainer/post-create.sh
  .eslintrc.js
  .github/renovate.json5
  Dockerfile
  Gemfile.lock
  app/controllers/accounts_controller.rb
  app/javascript/mastodon/components/admin/Trends.jsx
  app/javascript/mastodon/components/hashtag.jsx
  app/javascript/mastodon/components/hashtag.tsx
  app/javascript/mastodon/features/account/components/featured_tags.jsx
  app/javascript/mastodon/features/followed_tags/index.jsx
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/utils/__tests__/base64-test.ts
  app/javascript/mastodon/utils/__tests__/html-test.s
  app/javascript/mastodon/utils/config.js
  app/javascript/mastodon/utils/config.ts
  app/javascript/mastodon/utils/html.js
  app/javascript/mastodon/utils/html.ts
  app/javascript/mastodon/utils/icons.tsx
  app/javascript/mastodon/utils/log_out.ts
  app/javascript/mastodon/utils/notifications.js
  app/javascript/mastodon/utils/notifications.ts
  app/javascript/mastodon/utils/react_router.tsx
  app/javascript/mastodon/utils/scrollbar.ts
  app/mailers/admin_mailer.rb
  app/serializers/node_info/serializer.rb
  app/services/resolve_account_service.rb
  app/views/accounts/show.html.haml
  app/views/admin_mailer/new_appeal.text.erb
  app/views/admin_mailer/new_critical_software_updates.text.erb
  app/views/admin_mailer/new_pending_account.text.erb
  app/views/admin_mailer/new_report.text.erb
  app/views/admin_mailer/new_software_updates.text.erb
  app/views/admin_mailer/new_trends.text.erb
  app/views/layouts/admin_mailer.text.erb
  config/locales/nl.yml
  config/locales/ru.yml
  package.json
  spec/services/resolve_account_service_spec.rb
  streaming/.dockerignore
  streaming/.eslintrc.js
  streaming/Dockerfile
  streaming/index.js
  streaming/metrics.js
  streaming/package.json
  streaming/tsconfig.json
  streaming/utils.js
  yarn.lock
Labels: upstream

#316 Fix: スタンプを外すとき、自分が外したスタンプが投稿から全部消える問題 (9.1)
  app/models/status.rb
  app/services/un_emoji_react_service.rb
Labels: bug

#294 Add: #8 サークル投稿の転送
  app/controllers/activitypub/contexts_controller.rb
  app/javascript/mastodon/components/compacted_status.jsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/components/visibility_icon.tsx
  app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx
  app/javascript/mastodon/features/compose/containers/privacy_dropdown_container.js
  app/javascript/mastodon/features/status/components/action_bar.jsx
  app/javascript/mastodon/reducers/compose.js
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/delete.rb
  app/lib/activitypub/activity/update.rb
  app/lib/activitypub/parser/status_parser.rb
  app/lib/activitypub/tag_manager.rb
  app/lib/feed_manager.rb
  app/lib/status_reach_finder.rb
  app/models/conversation.rb
  app/models/status.rb
  app/policies/status_policy.rb
  app/serializers/activitypub/context_serializer.rb
  app/serializers/activitypub/note_serializer.rb
  app/services/concerns/payloadable.rb
  app/services/fan_out_on_write_service.rb
  app/services/post_status_service.rb
  app/services/process_conversation_service.rb
  app/services/remove_status_service.rb
  app/workers/activitypub/distribution_worker.rb
  app/workers/activitypub/forward_conversation_worker.rb
  app/workers/activitypub/status_update_distribution_worker.rb
  config/routes.rb
  db/migrate/20231115001356_add_inbox_url_to_conversations.rb
  db/schema.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/lib/activitypub/activity/delete_spec.rb
  spec/lib/activitypub/activity/update_spec.rb
  spec/models/status_spec.rb
  spec/policies/status_policy_spec.rb
  spec/services/fan_out_on_write_service_spec.rb
  spec/services/post_status_service_spec.rb
  spec/services/remove_status_service_spec.rb
  spec/workers/activitypub/distribution_worker_spec.rb
  spec/workers/activitypub/status_update_distribution_worker_spec.rb
Labels: server-test-requested

#318 Fix: `ancestor_status_id`検索によるDB負荷
  db/migrate/20231130031209_add_index_on_conversations_ancestor_status_id.rb
  db/schema.rb
Labels: load

#319 Fix: 他サーバーからの`conversation`が正常に認識されない問題
  app/lib/activitypub/activity/create.rb
Labels: bug

#320 Fix: 既知の投稿の参照・引用が認識されない問題
  app/lib/activitypub/activity/update.rb
  spec/services/process_references_service_spec.rb
Labels: bug

#321 Fix: 限定投稿新規追加時の負荷
  db/migrate/20231130083634_add_index_on_statuses_conversation_id.rb
  db/schema.rb
Labels: load
