Repository kmycode/mastodon, pull requests merged in 2024-04, with the labels that each got.

#688 Fix: 絵文字リアクションのストリーミングでエラーが発生する問題
  app/javascript/mastodon/reducers/statuses.js
Labels: bug

#693 Upstream 20240404
  .eslintrc.js
  app/javascript/mastodon/components/hashtag_bar.tsx
  app/javascript/mastodon/locales/et.json
  app/javascript/mastodon/locales/fil.json
  app/javascript/mastodon/locales/ia.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/lt.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/sq.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/uuid.ts
  app/javascript/packs/admin.tsx
  app/javascript/packs/public.tsx
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/emoji_picker.scss
  app/views/application/mailer/_feature.html.haml
  app/views/user_mailer/welcome.html.haml
  config/locales/ia.yml
  config/locales/sq.yml
  yarn.lock
Labels: upstream

#698 Add: 絵文字リアクション対応サーバーに`rosekey`
  app/models/instance_info.rb
Labels: enhancement

#700 Upstream 20240408
  Gemfile
  Gemfile.lock
  Vagrantfile
  app/helpers/application_helper.rb
  app/helpers/theme_helper.rb
  app/javascript/mastodon/utils/__tests__/html-test.ts
  app/javascript/mastodon/utils/__tests__/numbers.ts
  app/javascript/styles/mastodon/emoji_picker.scss
  app/lib/admin/metrics/measure/tag_servers_measure.rb
  app/lib/annual_report/top_statuses.rb
  app/lib/themes.rb
  app/models/concerns/custom_filter_cache.rb
  app/models/custom_filter_keyword.rb
  app/models/custom_filter_status.rb
  app/models/user.rb
  app/validators/email_address_validator.rb
  app/views/application/mailer/_feature.html.haml
  app/views/application/mailer/_hashtag.html.haml
  app/views/layouts/application.html.haml
  app/views/user_mailer/welcome.html.haml
  spec/helpers/theme_helper_spec.rb
  spec/lib/admin/metrics/dimension/languages_dimension_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/user_spec.rb
  spec/requests/api/web/embeds_spec.rb
  spec/system/oauth_spec.rb
  yarn.lock
Labels: upstream

#701 Remove: 投稿の引用一覧画面から引用表示
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/features/status_references/index.jsx
Labels: enhancement

#706 Fix: ホワイトリストのドメインリストが並べ替えされていない問題
  app/models/specified_domain.rb
Labels: bug

#707 Upstream 20240409
  app/controllers/concerns/cache_concern.rb
  app/javascript/mastodon/common.js
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/gd.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/lt.json
  app/lib/feed_manager.rb
  app/lib/vacuum/feeds_vacuum.rb
  app/models/concerns/account/interactions.rb
  app/models/concerns/cacheable.rb
  app/models/feed.rb
  app/models/public_feed.rb
  app/models/status.rb
  app/models/tag_feed.rb
  app/models/user.rb
  app/views/application/mailer/_hashtag.html.haml
  config/locales/ar.yml
  config/locales/devise.es.yml
  config/locales/devise.lt.yml
  config/locales/doorkeeper.lt.yml
  config/locales/doorkeeper.sr.yml
  config/locales/gd.yml
  config/locales/ja.yml
  config/locales/lt.yml
  config/locales/simple_form.ko.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  spec/controllers/application_controller_spec.rb
  spec/models/home_feed_spec.rb
  spec/models/user_spec.rb
  yarn.lock
Labels: upstream

#708 Fix: [WebUI] フルダークテーマの修正
  app/javascript/styles/full-dark/diff.scss
Labels: bug

#687 Release: 11.4
  AUTHORS_KB.md
  app/controllers/admin/statuses_controller.rb
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/reducers/compose.js
  app/javascript/styles/full-dark/diff.scss
  app/javascript/styles/mastodon/components.scss
  app/models/admin/status_batch_action.rb
  app/models/concerns/account/interactions.rb
  app/models/instance_info.rb
  app/models/trends/tags.rb
  app/services/approve_appeal_service.rb
  app/services/post_status_service.rb
  app/services/update_status_service.rb
  app/workers/activitypub/fetch_instance_info_worker.rb
  lib/mastodon/version.rb
  spec/models/trends/tags_spec.rb
  spec/services/post_status_service_spec.rb
  spec/services/update_status_service_spec.rb
Labels: release

#710 Upstream 20240412
  .haml-lint.yml
  Gemfile.lock
  app/helpers/context_helper.rb
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/tt.json
  config/locales/tt.yml
  lib/mastodon/cli/progress_helper.rb
  lib/templates/haml/scaffold/_form.html.haml.tt
  spec/fabricators/preview_card_provider_fabricator.rb
  spec/fabricators/unavailable_domain_fabricator.rb
Labels: upstream

#670 Fix: 連合リレー判定に、フレンドサーバーのチェックを追加
  app/lib/activitypub/activity.rb
Labels: bug, federation

#715 Add: 絵文字リアクション利用可能なソフトウェアに`tanukey`
  app/models/instance_info.rb
Labels: enhancement

#721 Refactor: インスタンスで利用可能な機能を検出する処理
  app/models/instance_info.rb
  spec/models/instance_info_spec.rb
Labels: refactoring

#725 Add: fep-e232引用仕様
  app/lib/activitypub/activity/create.rb
  app/serializers/activitypub/note_serializer.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/serializers/activitypub/note_serializer_spec.rb
Labels: enhancement

#719 Remove: 絵文字リアクション対応サーバーに`rosekey`
  app/models/instance_info.rb
Labels: enhancement

#730 Change: 自動セットアップスクリプトを改善
  install/12.0/setup-imagemagick-7.sh
  install/12.0/setup1.sh
  install/12.0/setup2.sh
Labels: enhancement

#734 Upstream 20240426
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/features/explore/components/card.jsx
  app/javascript/mastodon/features/explore/suggestions.jsx
  app/javascript/mastodon/features/notifications/components/moderation_warning.tsx
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/styles/mastodon/components.scss
  app/models/admin/account_action.rb
  app/models/admin/status_batch_action.rb
  app/models/notification.rb
  app/serializers/rest/account_warning_serializer.rb
  app/serializers/rest/appeal_serializer.rb
  app/serializers/rest/notification_serializer.rb
  app/services/notify_service.rb
  config/locales/en.yml
  config/locales/ja.yml
  db/migrate/20240426000034_move_account_warning_notifications.rb
  db/schema.rb
  lib/tasks/dangerous.rake
  spec/models/admin/account_action_spec.rb
Labels: upstream

#735 Fix: モデレーターが投稿を編集するとき、編集したアカウントを保存する処理においてkmy.blueサーバー向け個別設定を削除
  app/controllers/admin/statuses_controller.rb
Labels: bug, backport

#736 Upstream 20240427
  .gitignore
  Gemfile.lock
  app/javascript/mastodon/actions/markers.ts
  app/javascript/mastodon/features/notifications/components/moderation_warning.tsx
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fo.json
  app/javascript/mastodon/locales/gd.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/is.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/nn.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-PT.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-TW.json
  app/javascript/material-icons/400-24px/gavel-fill.svg
  app/javascript/material-icons/400-24px/gavel.svg
  app/models/notification.rb
  app/serializers/rest/notification_serializer.rb
  app/services/post_status_service.rb
  app/views/admin/settings/content_retention/show.html.haml
  config/locales/de.yml
  config/locales/doorkeeper.pt-PT.yml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.ja.yml
  db/migrate/20240426233435_migrate_moderation_warning_notifications_from_account.rb
  db/schema.rb
  lib/tasks/dangerous.rake
  package.json
  spec/models/notification_spec.rb
  spec/services/post_status_service_spec.rb
  streaming/package.json
  yarn.lock
Labels: upstream
