Repository kmycode/mastodon, pull requests merged in 2024-03, with the labels that each got.

#625 Change: #556 ドメインブロック「フォローされていない相手からのリプライを拒否」に、参照を含める
  app/services/activitypub/process_status_update_service.rb
  config/locales/en.yml
  config/locales/ja.yml
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: refactoring

#623 Change: NGルール・NGワードのテキストマッチはHTMLタグを除外する
  app/models/admin/ng_rule.rb
  app/models/admin/ng_word.rb
  spec/lib/activitypub/activity/create_spec.rb
Labels: specchange

#629 Change: 一般ユーザーはデフォルトで招待を不可にするよう変更
  app/models/user_role.rb
  config/roles.yml
  spec/models/user_role_spec.rb
Labels: specchange

#632 Fix: 新規登録設定画面の有効・無効判定条件ミス
  app/javascript/packs/admin.tsx
Labels: bug

#633 Add: 管理画面で特に負荷の大きい処理を無効にする環境変数
  app/helpers/high_load_helper.rb
  app/javascript/mastodon/components/admin/Counter.jsx
  app/javascript/mastodon/components/admin/Dimension.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/ja.json
  app/lib/admin/metrics/dimension.rb
  app/lib/admin/metrics/measure.rb
Labels: bug, enhancement

#635 Add: 管理画面での操作履歴フィルタにkmyblue独自項目、カスタム絵文字に編集画面へのリンク
  app/helpers/admin/action_logs_helper.rb
  app/models/admin/action_log_filter.rb
  config/locales/en.yml
  config/locales/ja.yml
Labels: enhancement

#640 Upstream 20240306
  Gemfile.lock
  app/models/account_suggestions/friends_of_friends_source.rb
  app/models/account_suggestions/similar_profiles_source.rb
  app/models/account_suggestions/source.rb
  package.json
  spec/models/account_suggestions/friends_of_friends_source_spec.rb
  spec/models/account_suggestions/source_spec.rb
  streaming/package.json
  yarn.lock
Labels: upstream

#639 Change: ユーザー設定の複数の項目を反転
  app/controllers/filters_controller.rb
  app/models/custom_filter.rb
  app/models/user_settings.rb
  app/models/user_settings/namespace.rb
  app/views/filters/_filter_fields.html.haml
  app/views/settings/preferences/appearance/show.html.haml
  app/views/settings/privacy/show.html.haml
  config/locales/simple_form.en.yml
  config/locales/simple_form.ja.yml
Labels: enhancement

#644 Upstream 20240307
  app/javascript/mastodon/features/compose/containers/upload_button_container.js
  app/models/account_suggestions/friends_of_friends_source.rb
  app/models/account_suggestions/similar_profiles_source.rb
  app/models/account_suggestions/source.rb
  spec/models/account_suggestions/friends_of_friends_source_spec.rb
  spec/models/account_suggestions/source_spec.rb
Labels: upstream

#485 Fix: Streaming用Dockerfile分離に合わせたComposeファイルの修正
  docker-compose.yml
Labels: bug

#643 Add: 貢献者一覧を更新
  AUTHORS_KB.md
Labels: release

#652 Release: 11.3
  lib/mastodon/version.rb
Labels: release

#651 Bump version to 12.0-dev
  lib/mastodon/version.rb
Labels: enhancement

#650 Change: #532 ElasticSearch設定の外出し
  .gitignore
  app/chewy/accounts_index.rb
  app/chewy/public_statuses_index.rb
  app/chewy/statuses_index.rb
  app/chewy/tags_index.rb
  app/lib/chewy_config.rb
  config/elasticsearch.default-ja-sudachi.yml
  config/elasticsearch.default.yml
  config/initializers/chewy.rb
Labels: server-test-requested

#658 Add: 貢献者
  AUTHORS_KB.md
Labels: release

#661 Fix: センシティブワードの仕様変更を本家に戻すスクリプトへ反映
  lib/tasks/dangerous.rake
Labels: bug

#672 Change: フィールド入力フォームのデザイン改善
  app/javascript/styles/mastodon/forms.scss
  app/views/settings/profiles/show.html.haml
  config/locales/simple_form.en.yml
  config/locales/simple_form.ja.yml
Labels: enhancement

#675 Fix: 本番環境でNGワードとセンシティブワードの編集が反映されない問題
  app/models/ng_word.rb
  app/models/sensitive_word.rb
Labels: bug

#676 Fix: ドメインブロックのトレンド掲載を拒否に、ハッシュタグが含まれない問題
  app/models/trends/tags.rb
  spec/models/trends/tags_spec.rb
Labels: bug

#685 Fix: 投稿にNGワードが含まれる場合、投稿のモデレーションができなくなる場合がある問題
  app/controllers/admin/statuses_controller.rb
  app/models/admin/status_batch_action.rb
  app/services/approve_appeal_service.rb
  app/services/update_status_service.rb
  spec/services/update_status_service_spec.rb
Labels: bug

#681 Fix: `threads.net`のインスタンス情報のフェッチが止まらない問題
  app/workers/activitypub/fetch_instance_info_worker.rb
Labels: bug
